#!/usr/bin/env python3
"""
Generate a skill draft from a detected ritual pattern.

Usage:
    ./generate_skill_draft.py --prompt "run cargo clippy" --count 47 --workspace /data/projects/rust_porting_system
    ./generate_skill_draft.py --prompt "use --fields minimal" --count 23 --output draft.md
"""

import argparse
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def slugify(text: str) -> str:
    """Convert text to a slug suitable for skill names."""
    # Lowercase and replace non-alphanumeric with hyphens
    slug = re.sub(r'[^a-z0-9]+', '-', text.lower())
    # Remove leading/trailing hyphens
    slug = slug.strip('-')
    # Limit length
    return slug[:50]


def find_instances(workspace: str, prompt: str, limit: int = 5) -> list[dict]:
    """Find concrete instances of a prompt pattern."""
    cmd = [
        "cass", "search", prompt,
        "--workspace", workspace,
        "--json",
        "--fields", "minimal",
        "--limit", str(limit * 3)  # Get extra to filter
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        return []

    import json
    data = json.loads(result.stdout)
    hits = data.get("hits", [])

    # Filter to user prompts and take first N
    instances = []
    for hit in hits:
        if hit.get("line_number", 999) <= 3:
            instances.append({
                "source_path": hit.get("source_path", ""),
                "title": hit.get("title", ""),
                "line_number": hit.get("line_number", 0)
            })
            if len(instances) >= limit:
                break

    return instances


def generate_draft(prompt: str, count: int, workspace: str, instances: list[dict]) -> str:
    """Generate a skill draft markdown."""
    slug = slugify(prompt)
    name = slug.replace('-', ' ').title()

    # Format instances for provenance
    provenance_lines = []
    for inst in instances[:5]:
        path = inst.get("source_path", "unknown")
        provenance_lines.append(f"- `{path}`")

    provenance = "\n".join(provenance_lines) if provenance_lines else "- (instances not retrieved)"

    draft = f'''---
name: {slug}
description: >-
  [TODO: One sentence describing when to use this pattern]
---

# {name}

> **Core Insight:** [TODO: The generalized rule extracted from {count} instances]

## When to Use

- [TODO: Trigger condition 1]
- [TODO: Trigger condition 2]
- [TODO: Trigger condition 3]

## THE EXACT PROMPT

```
{prompt}
```

## Why This Works

[TODO: Explanation derived from successful instances]

This pattern appeared {count} times in your session history, indicating it's a
validated part of your methodology.

## Pitfalls (When NOT to Use)

- [TODO: Counter-example 1 - when this doesn't apply]
- [TODO: Counter-example 2]

## Provenance

Extracted from {count} sessions in `{workspace}`:
{provenance}

---

*Generated by learning-flywheel on {datetime.now().strftime("%Y-%m-%d")}*
*Review and refine the [TODO] sections before publishing.*
'''
    return draft


def main():
    parser = argparse.ArgumentParser(
        description="Generate a skill draft from a ritual pattern"
    )
    parser.add_argument(
        "--prompt", "-p",
        required=True,
        help="The ritual prompt pattern"
    )
    parser.add_argument(
        "--count", "-c",
        type=int,
        required=True,
        help="Number of times this pattern appeared"
    )
    parser.add_argument(
        "--workspace", "-w",
        default="",
        help="Workspace to search for instances"
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file for the draft (default: stdout)"
    )

    args = parser.parse_args()

    # Find instances if workspace provided
    instances = []
    if args.workspace:
        print(f"Finding instances in {args.workspace}...", file=sys.stderr)
        instances = find_instances(args.workspace, args.prompt)
        print(f"Found {len(instances)} instances", file=sys.stderr)

    # Generate draft
    draft = generate_draft(args.prompt, args.count, args.workspace, instances)

    if args.output:
        Path(args.output).write_text(draft)
        print(f"Wrote draft to {args.output}")
    else:
        print(draft)


if __name__ == "__main__":
    main()
